### ISSUE TITLE
Prebuild binaries

### ISSUE THREAD

**Issue by ooxi** [client9/dmnt#2]
Just wanting to let you know, having prebuild binaries would be nice :-)

also releases / tags :-)

-- ooxi

**Comment by client9** [comment]
Hi @ooxi 

Sorry for the delay.. notifications all seemed to stop for me :-(

if you still use this, i'm happy to add prebuilt binaries and versions.

My problem is that mid-2017 the file sync between mac and the container was too slow.  But it might be better now.

**Comment by ooxi** [comment]
Thanks for the comeback :-) however I'm no longer using dmnt.

But maybe prebuild binaries would be nice for other users, too.

Nevertheless, I'm closing this task, since I'm currently not in need for prebuild binaries.
